(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var V0=function(a){a.ea("cardstatechange",a.Qh()&&a.Ol()?1:0)},W0=function(a,b){var c=g.Ma(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},LTa=function(a){var b=g.Wm(a);
a=g.Zm(a);return new g.Lm(b.x,b.y,a.width,a.height)},MTa=function(a){return Math.pow(a,3)},NTa=function(a){return 3*a*a-2*a*a*a},Z0=function(a){a=g.Qa(a);
delete X0[a];g.Xf(X0)&&Y0&&Y0.stop()},PTa=function(){Y0||(Y0=new g.L(function(){OTa()},20));
var a=Y0;a.isActive()||a.start()},OTa=function(){var a=g.Ua();
g.Jf(X0,function(b){QTa(b,a)});
g.Xf(X0)||PTa()},$0=function(a,b,c,d){g.Qp.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.u=a;this.S=b;this.duration=c;this.J=d;this.coords=[];this.progress=this.K=0;this.D=null},QTa=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.K=1E3/(b-a.D);a.D=b;RTa(a,a.progress);1==a.progress?(a.j=0,Z0(a),a.onFinish(),a.Sy()):a.Nc()&&a.sE()},RTa=function(a,b){"function"===typeof a.J&&(b=a.J(b));
a.coords=Array(a.u.length);for(var c=0;c<a.u.length;c++)a.coords[c]=(a.S[c]-a.u[c])*b+a.u[c]},STa=function(a,b){g.zf.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.K;this.state=b.j},a1=function(a,b,c,d,e){$0.call(this,b,c,d,e);
this.element=a},b1=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
a1.call(this,a,b,c,d,e)},c1=function(a){g.G.call(this);
this.u=a||window;this.j=[]},d1=function(a){return a.baseUrl||null},e1=function(a,b){return g.Zn(g.Zl(a,b),function(c){return!!c})},TTa=function(a,b,c){function d(Na){var va=Na.hovercardButton;
if(!va)return null;va=va.subscribeButtonRenderer;if(!va)return null;var Cb=f(va.unsubscribedButtonText),jb=f(va.subscribedButtonText);if(va.subscribed){var lc=f(va.subscriberCountWithUnsubscribeText);var uc=f(va.subscriberCountText)}else lc=f(va.subscriberCountText),uc=f(va.subscriberCountWithSubscribeText);var Wc=null;if(Na.signinEndpoint){Wc=W0(Na,"signinEndpoint","webNavigationEndpointData","url");if(!Wc){var Hd,$e,Ra;Wc=null==(Hd=va.signInEndpoint)?void 0:null==($e=Hd.commandMetadata)?void 0:
null==(Ra=$e.webCommandMetadata)?void 0:Ra.url}if(!Wc)return null}return Cb&&(jb||Wc)?{subscribed:va.subscribed,subscribeText:Cb,subscribeCount:lc,unsubscribeText:jb,unsubscribeCount:uc,enabled:va.enabled,signinUrl:Wc,classic:Na.useClassicSubscribeButton}:null}
function e(Na){if(Na){var va=[],Cb=Na.videoId;Cb&&va.push("v="+Cb);(Cb=Na.playlistId)&&va.push("list="+Cb);(Na=Na.startTimeSeconds)&&va.push("t="+Na);return"/watch?"+va.join("&")}}
function f(Na){if(!Na)return null;var va=Na.simpleText;return va?va:Na.runs?g.Zl(Na.runs,function(Cb){return Cb.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var k=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,t=null,v=null,x=null,y=!1,z=null,E=null,I=null,K=null,P=null,Y=null;if("VIDEO"===k)l.urlEndpoint?m=l.urlEndpoint.url:(Y=l.watchEndpoint,m=e(Y)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,t=f(p.text),p="LIVE"===p.style):t=f(b.videoDuration);else if("PLAYLIST"===k)l.urlEndpoint?m=l.urlEndpoint.url:(Y=l.watchEndpoint,m=e(Y)),n=!1,q=a,v=f(b.playlistLength);
else if("CHANNEL"===k){if(y=W0(l,"browseEndpoint","browseId"))x=y,m="/channel/"+x;n=!1;q="new";(y=!!b.isSubscribe)?z=d(b):E=f(b.subscribersText)}else"WEBSITE"===k?((I=W0(l,"urlEndpoint","url"))&&(m=I),n=!0,q="new",I=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===k&&(b.productPrice&&(K=f(b.productPrice)),b.additionalFeesText&&(P=f(b.additionalFeesText)),(n=W0(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=W0(b,"title","accessibility","accessibilityData","label");var J=b.endpoint?b.endpoint.clickTrackingParams:
null,pa="";if(b.metadata){var za=f(b.metadata);za&&(pa=za)}return{id:"element-"+c,type:k,title:f(b.title),metadata:pa,callToAction:f(b.callToAction),WM:b.image,iconUrl:I,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:t,isLiveVideo:p,playlistLength:v,channelId:x,subscribeButton:z,subscribersText:E,isSubscribe:y,targetUrl:m||null,HW:n,sessionData:J?{itct:J}:null,q0:q,
ex:a?a:null,isPlaceholder:b.isPlaceholder,impressionUrls:e1(b.impressionUrls||[],d1),uW:e1(b.hovercardShowUrls||[],d1),clickUrls:e1(l.loggingUrls||[],d1),visualElement:g.Ov(b.trackingParams),productPrice:K,additionalFeesText:P,watchEndpoint:Y||null}},f1=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:e1(a.impressionUrls||[],d1),elements:e1(a.elements||[],function(d,e){return TTa(b,d,e)})};
a.trackingParams&&(c.visualElement=g.Ov(a.trackingParams));return c},g1=function(a){g.oL.call(this,a);
this.B=this.endscreen=null;this.j={};this.D={};this.C=this.u=null;this.K=[];this.Y=!0;this.J=0;a=a.V();this.S=g.zC(a)||g.DC(a);this.events=new g.lA(this);g.H(this,this.events);this.events.T(this.player,g.Nw("creatorendscreen"),this.onCueRangeEnter);this.events.T(this.player,g.Ow("creatorendscreen"),this.onCueRangeExit);this.events.T(this.player,"resize",this.xb);this.events.T(window,"focus",this.n_);this.load();var b=g.ji("STYLE");(g.Xh("HEAD")[0]||document.body).appendChild(b);g.yf(this,function(){g.ni(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},UTa=function(a){return a.player.getVideoData().D?"current":a.S?"new":"current"},h1=function(a){return"creator-endscreen-editor"===a.player.V().playerStyle},VTa=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.B&&a.B.abort();c={method:"POST",onFinish:function(e){var f=a.B=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=f1(f,UTa(a))));i1(a,f)},
urlParams:{v:c},withCredentials:!0};a.S&&(c.urlParams.ptype="embedded");var d=b.Sr;d&&(c.postParams={ad_tracking:d});if(b=g.owa(b))if(b=g.ah(b),b=g.Xg(b))a.B=g.Ir(b,c)},i1=function(a,b,c){c=void 0===c?!0:c;
a.player.Nf("creatorendscreen");a.u&&(a.u.dispose(),a.u=null,a.C.dispose(),a.C=null);for(var d=g.r(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.D={};0<a.K.length&&(a.K.forEach(function(l){l.dispose()}),a.K.length=0);
a.J=0;if((a.endscreen=b)&&b.elements){c&&WTa(a);c=[];d=new g.Lw(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.V().isMobile||(a.u=new g.V({G:"div",L:"ytp-ce-shadow"}),g.bL(a.player,a.u.element,4),a.C=new g.XI(a.u,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=XTa(a,e);if(f){a.j[e.id]=f;a.D[e.id]=e;g.bL(a.player,f.element,4);var k=new g.Lw(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(k);YTa(a,
f,e)}else g.Lv(new g.Ks("buildEndscreenElement null",e))}a.player.je(c);a.xb()}},WTa=function(a){var b=g.Uv(),c=g.Vv();
c&&b&&a.endscreen.visualElement&&g.Zv(void 0,c,b,[a.endscreen.visualElement])},XTa=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={G:"div",Ea:["ytp-ce-element","ytp-ce-video"],W:{tabindex:"0","aria-label":b.ex||"","aria-hidden":"true"},U:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-covering-image",W:j1(b)},{G:"div",L:"ytp-ce-covering-shadow-top"},{G:"a",L:"ytp-ce-covering-overlay",W:{href:k1(a,b.targetUrl),tabindex:"-1"},U:[{G:"div",Ea:["ytp-ce-video-title","ytp-webkit-ellipsis"],W:{dir:g.Up(b.title||"")},oa:b.title},{G:"div",L:b.isLiveVideo?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
oa:b.videoDuration||void 0}]}]};c=new g.V(a);break;case "PLAYLIST":a={G:"div",Ea:["ytp-ce-element","ytp-ce-playlist"],W:{tabindex:"0","aria-label":b.ex||"","aria-hidden":"true"},U:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-covering-image",W:j1(b)},{G:"div",L:"ytp-ce-covering-shadow-top"},{G:"a",L:"ytp-ce-covering-overlay",W:{href:k1(a,b.targetUrl),tabindex:"-1"},U:[{G:"div",Ea:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],W:{dir:g.Up(b.title||"")},oa:b.title},{G:"div",L:"ytp-ce-playlist-count",
U:[{G:"div",L:"ytp-ce-playlist-icon"},{G:"div",L:"ytp-ce-playlist-count-text",oa:b.playlistLength||void 0}]}]}]};c=new g.V(a);break;case "CHANNEL":c={G:"div",Ea:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],W:{tabindex:"0","aria-label":b.ex||"","aria-hidden":"true"},U:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-expanding-overlay",U:[{G:"div",L:"ytp-ce-expanding-overlay-hider"},{G:"div",L:"ytp-ce-expanding-overlay-background"},{G:"div",L:"ytp-ce-expanding-overlay-content",
U:[{G:"div",L:"ytp-ce-expanding-overlay-body",U:[{G:"div",L:"ytp-ce-expanding-overlay-body-padding",U:[{G:"a",Ea:["ytp-ce-channel-title","ytp-ce-link"],W:{href:k1(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.Up(b.title||"")},oa:b.title},b.subscribeButton?{G:"div",L:"ytp-ce-subscribe-container",U:[{G:"div",L:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{G:"div",L:"ytp-ce-channel-subscribers-text",oa:b.subscribersText}:"",b.metadata?{G:"div",Ea:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],oa:b.metadata}:""]}]}]}]},{G:"div",L:"ytp-ce-expanding-image",W:j1(b)}]};c=new g.V(c);var d=g.Yh(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.M(d,"ytp-ce-subscribe-button");if(a.player.V().isMobile){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.tM(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,
!!b.subscribeButton.classic,b.channelId,!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.K.push(e)}break;case "WEBSITE":a={G:"div",Ea:["ytp-ce-element","ytp-ce-website"],W:{tabindex:"0","aria-label":b.ex||"","aria-hidden":"true"},U:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-expanding-overlay",U:[{G:"div",L:"ytp-ce-expanding-overlay-hider"},{G:"div",L:"ytp-ce-expanding-overlay-background"},{G:"div",L:"ytp-ce-expanding-overlay-content",
U:[{G:"div",L:"ytp-ce-expanding-overlay-body",U:[{G:"div",L:"ytp-ce-expanding-overlay-body-padding",U:[{G:"div",L:"ytp-ce-website-title",W:{dir:g.Up(b.title||"")},oa:b.title},{G:"div",L:"ytp-ce-website-metadata",oa:b.metadata},{G:"a",Ea:["ytp-ce-website-goto","ytp-ce-link"],W:{href:k1(a,b.targetUrl),target:"_blank",tabindex:"-1"},oa:b.callToAction}]}]}]}]},{G:"div",L:"ytp-ce-expanding-image",W:j1(b)},{G:"div",L:"ytp-ce-expanding-icon",W:ZTa(b.iconUrl)}]};c=new g.V(a);break;case "CREATOR_MERCHANDISE":c=
"",b.productPrice&&(c={G:"div",L:"ytp-ce-merchandise-price-container",U:[{G:"div",L:"ytp-ce-merchandise-price",oa:b.productPrice}]},b.additionalFeesText&&c.U.push({G:"div",L:"ytp-ce-merchandise-additional-fees",oa:b.additionalFeesText})),a={G:"div",Ea:["ytp-ce-element","ytp-ce-merchandise"],W:{tabindex:"0","aria-label":b.ex||"","aria-hidden":"true"},U:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-expanding-overlay",U:[{G:"div",L:"ytp-ce-expanding-overlay-hider"},{G:"div",L:"ytp-ce-expanding-overlay-background"},
{G:"div",L:"ytp-ce-expanding-overlay-content",U:[{G:"div",L:"ytp-ce-expanding-overlay-body",U:[{G:"div",L:"ytp-ce-expanding-overlay-body-padding",U:[{G:"div",L:"ytp-ce-merchandise-title",W:{dir:g.Up(b.title||"")},oa:b.title},c,{G:"div",L:"ytp-ce-merchandise-metadata",oa:b.metadata},{G:"a",Ea:["ytp-ce-merchandise-goto","ytp-ce-link"],W:{href:k1(a,b.targetUrl),target:"_blank",tabindex:"-1"},oa:b.callToAction}]}]}]}]},{G:"div",L:"ytp-ce-expanding-image",W:j1(b)},{G:"div",L:"ytp-ce-merchandise-invideo-cta-container",
U:[{G:"div",L:"ytp-ce-merchandise-invideo-cta",oa:b.callToAction||void 0}]}]},c=new g.V(a)}b.isPlaceholder&&g.M(c.element,"ytp-ce-placeholder");return c},j1=function(a){if(a.WM)var b=a.WM.thumbnails;
return ZTa(b?b[b.length-1].url:null)},ZTa=function(a){return a?{style:"background-image: url("+a+")"}:{}},YTa=function(a,b,c){function d(m){m&&(b.Na("blur",function(){"none"!=m.style.display&&a.Y&&m.focus()}),b.T(m,"focus",f),b.T(m,"blur",k))}
function e(m){a.J+=m;0<a.J?(g.M(b.element,"ytp-ce-force-expand"),l1(a,c.id,!0)):(g.Hp(b.element,"ytp-ce-force-expand"),g.Hp(b.element,"ytp-ce-element-hover"),l1(a,c.id,!1))}
function f(){e(1)}
function k(){e(-1)}
b.Na("mouseenter",function(){m1(a,b,c)});
b.Na("mouseleave",function(){n1(a,b,c)});
a.player.V().isMobile||b.Na("click",function(){g.M(b.element,"ytp-ce-element-hover")});
b.Na("click",function(m){$Ta(a,c,m)});
b.Na("keypress",function(m){$Ta(a,c,m)});
b.Na("focus",function(){m1(a,b,c)});
b.Na("blur",function(){n1(a,b,c)});
b.Na("touchstart",function(){m1(a,b,c)});
var l=g.ci("ytp-ce-expanding-overlay-hider",b.element);l&&b.T(l,"touchstart",function(m){m=m||window.event;m.cancelBubble=!0;m.stopPropagation&&m.stopPropagation();g.Hp(b.element,"ytp-ce-element-hover");g.Hp(b.element,"ytp-ce-force-expand")});
b.Na("keydown",function(m){a.Y=9===m.keyCode&&!m.shiftKey});
d(g.ci("ytp-sb-subscribe",b.element));d(g.ci("ytp-sb-unsubscribe",b.element));b.Na("focus",f);b.Na("blur",k)},$Ta=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.Fp(d,"ytp-ce-element");){g.Fp(d,"subscribe-label")&&o1(a,b);
if(g.Fp(d,"ytp-ce-channel-subscribe"))return;d=g.oi(d)}if(!d||g.Fp(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])n1(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.q0)o1(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.ah(k1(a,b.targetUrl)),g.wJ(g.Xg(c),void 0,b.sessionData);else{var e=g.TC(a.player.V())||a.player.getVideoData().D,f=function(){var k=k1(a,b.targetUrl),l=b.sessionData,m=b.watchEndpoint,n=g.qr(k);e&&n&&(n.v||n.list)?
a.player.ql(n.v,l,n.list,!1,void 0,m||void 0):g.vJ(k,l)};
o1(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},k1=function(a,b){a=a.player.V();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.dD(a)+b}else return"";return b},m1=function(a,b,c){g.Fp(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.M(b.element,"ytp-ce-element-hover"):a.player.V().isMobile?(new g.L(function(){g.M(b.element,"ytp-ce-element-hover")},200)).start():g.M(b.element,"ytp-ce-element-hover"),p1(a,c.uW),l1(a,c.id,!0))},n1=function(a,b,c){g.Hp(b.element,"ytp-ce-element-hover");
g.Hp(b.element,"ytp-ce-force-expand");l1(a,c.id,!1)},l1=function(a,b,c){a.u&&(c?a.C.show():a.C.hide());
for(var d=g.r(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.N(a.j[e].element,"ytp-ce-element-shadow-show",c)},p1=function(a,b,c){function d(){f||(e++,e===b.length&&(k.stop(),c&&c()))}
if(!b||0===b.length||h1(a))c&&c();else{b=aUa(a,b);var e=0,f=!1,k=new g.L(function(){f=!0;c&&c()},1E3,a);
k.start();for(a=0;a<b.length;a++)g.Pt(b[a],d)}},o1=function(a,b,c){p1(a,b.clickUrls,c);
(a=g.Vv())&&b.HW&&g.ew(a,b.visualElement)},aUa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(bUa(b[d],c));return a},bUa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},cUa=function(a){return"string"===typeof a?a:""},q1=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},dUa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},r1=function(a){return a.value?a.value:null},s1=function(a){if(!a)return null;
var b=g.ah(cUa(a.value));b=g.Xg(b);if(!b)return null;var c=q1(a.target,eUa,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new dUa(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},fUa=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},iUa=function(a){if(!a)return null;
var b=q1(a.type,gUa),c=q1(a.trigger,hUa);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=s1(a?a:null);return b?new fUa(b,c,a):null},jUa=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},lUa=function(a){return(a=kUa(a,function(b){return"openUrl"===b.type&&null!=b.url}))?a.url:null},kUa=function(a,b){return g.Qb(a.action,b)},mUa=function(a,b){this.context=a;
this.j=b},u1=function(a){return a.customMessage?t1("div","iv-card-message",a.customMessage):""},v1=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{G:"div",L:"iv-card-image",W:{style:a},U:c}},w1=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.r(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(t1("li","",c.value));return{G:"ul",L:"iv-card-meta-info",U:b}},t1=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.Up(c);return{G:a,W:b,oa:c}},nUa=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.nx&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.nx+");");c.dir=g.Up(a.customMessage);var d=[{G:"span",oa:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({G:"span",L:"iv-card-link-icon"}));return{G:"div",Ea:b,W:c,U:d}},x1=function(a,b,c,d){if(d){b=g.r(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.tracking.click,5)}},oUa=function(a,b){this.merchant=a;
this.price=b},pUa=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},qUa=function(a,b){return b?b:pUa(a)?"current":"new"},y1=function(a,b){g.G.call(this);
var c=this;this.element=a;this.context=b;this.kb=!1;this.Ua=new Map;this.Za=new Map;this.context.I.addEventListener(g.Nw("annotations_module"),function(d){(d=c.Ua.get(d))&&d.apply(c)});
this.context.I.addEventListener(g.Ow("annotations_module"),function(d){(d=c.Za.get(d))&&d.apply(c)})},z1=function(a,b,c,d,e,f,k){a.context.j.Na(b,"click",function(l){a.tE(c,d,e,f||[],k||0,l)});
a.context.j.Na(b,"touchstart",function(){a.kb=!1});
a.context.j.Na(b,"touchmove",function(){a.kb=!0})},rUa=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},A1=function(a,b,c){return{impression:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
kR:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
nD:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},D1=function(a,b,c){y1.call(this,b,c);
var d=this;this.I=a;this.eventId=null;this.Ma=this.Jb=this.B=this.isInitialized=!1;this.va=null;this.cards=[];this.qb=this.S=this.Ia=this.D=this.Ta=this.j=null;this.Z=[];this.ma=this.K=this.lf=this.Ga=null;this.J=0;this.ya=new g.L(function(){},c.X.df?4E3:3E3);
g.H(this,this.ya);this.ib=new g.L(function(){});
g.H(this,this.ib);this.ra=new mUa(c,function(e,f,k,l,m,n){z1(d,e,f,k,l,m,n)});
this.Y=new g.V({G:"div",L:"iv-drawer",W:{id:"iv-drawer"},U:[{G:"div",L:"iv-drawer-header",W:{"aria-role":"heading"},U:[{G:"span",L:"iv-drawer-header-text"},{G:"button",Ea:["iv-drawer-close-button","ytp-button"],W:{"aria-label":"Hide cards",tabindex:"0"}}]},{G:"div",L:"iv-drawer-content"}]});g.H(this,this.Y);this.C=this.Y.element;this.gb=new g.XI(this.Y,330);g.H(this,this.gb);this.Hb=g.ci("iv-drawer-header-text",this.C);this.u=g.ci("iv-drawer-content",this.C);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.Jb&&B1(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Jb=d.B)&&C1(d)});
this.I.addEventListener("videodatachange",this.Fp.bind(this))},sUa=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){B1(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){C1(a)});
var c=b.headerText;g.qi(a.Hb,c);a.S&&a.S.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Ga=g.Ov(b.trackingParams);a.K=g.Ov(b.closeTrackingParams);a.lf=g.Ov(b.iconTrackingParams)},tUa=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.J,d=a.I.V().experiments.jb("enable_error_corrections_infocard");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){d=b.teaser.simpleCardTeaserRenderer;var e=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"simple",teaserText:g.Sw(d.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,tracking:{},Pl:null,gj:d.trackingParams?g.Ov(d.trackingParams):null,lf:e&&e.trackingParams?g.Ov(e.trackingParams):null,imageUrl:"",displayDomain:null,
showLinkIcon:!1,nx:null,title:"",customMessage:"",url:null,onClickCommand:d.onTapCommand||null};E1(a,b)}else if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"simple",teaserText:g.Sw(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:F1(a,
c,b,d),sponsored:!1,tracking:A1(d,e,d.command),Pl:d.trackingParams?g.Ov(d.trackingParams):null,gj:e.trackingParams?g.Ov(e.trackingParams):null,lf:f&&f.trackingParams?g.Ov(f.trackingParams):null,imageUrl:G1(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.Sw(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,nx:null,title:d.title?g.Sw(d.title):"",customMessage:d.callToAction?g.Sw(d.callToAction):"",url:d.command.urlEndpoint.url?s1({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:d.command.urlEndpoint.url}):null,onClickCommand:null};E1(a,b)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"collaborator",teaserText:g.Sw(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:F1(a,
c,b,d),sponsored:!1,tracking:A1(d,e,d.endpoint),Pl:d.trackingParams?g.Ov(d.trackingParams):null,gj:e.trackingParams?g.Ov(e.trackingParams):null,lf:f&&f.trackingParams?g.Ov(f.trackingParams):null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.Sw(d.customText):null,profileImageUrl:G1(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.Sw(d.channelName):"",metaInfo:[d.subscriberCountText?g.Sw(d.subscriberCountText):""],url:s1({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId}),onClickCommand:null};E1(a,b)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"playlist",teaserText:g.Sw(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:F1(a,c,b,d),sponsored:!1,tracking:A1(d,e,d.action),Pl:d.trackingParams?g.Ov(d.trackingParams):null,gj:e.trackingParams?g.Ov(e.trackingParams):null,lf:f&&f.trackingParams?g.Ov(f.trackingParams):null,Nz:G1(d.playlistThumbnail.thumbnails,258).url,customMessage:d.customMessage?g.Sw(d.customMessage):null,playlistVideoCount:g.Sw(d.playlistVideoCount),title:d.playlistTitle?g.Sw(d.playlistTitle):"",metaInfo:[d.channelName?
g.Sw(d.channelName):"",d.videoCountText?g.Sw(d.videoCountText):""],url:s1({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:rUa(d.action)}),onClickCommand:null};E1(a,b)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.videoInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"video",teaserText:g.Sw(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:F1(a,c,b,d),sponsored:!1,tracking:A1(d,e,d.action),Pl:d.trackingParams?g.Ov(d.trackingParams):null,gj:e.trackingParams?g.Ov(e.trackingParams):null,lf:f&&f.trackingParams?g.Ov(f.trackingParams):null,Nz:G1(d.videoThumbnail.thumbnails,258).url,videoDuration:d.lengthString?g.Sw(d.lengthString):null,customMessage:d.customMessage?g.Sw(d.customMessage):null,title:d.videoTitle?g.Sw(d.videoTitle):"",metaInfo:[d.channelName?
g.Sw(d.channelName):"",d.viewCountText?g.Sw(d.viewCountText):""],isLiveNow:!!d.badge,url:s1({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:rUa(d.action)}),onClickCommand:null};E1(a,b)}a.J++},G1=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},F1=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},vUa=function(a,b){if(b=uUa(a,b))b===a.j&&(a.j=null),a.I.removeCueRange(b.card.id),g.ni(b.qF),g.Yb(a.cards,b),a.HA(),H1(a)},B1=function(a,b,c){if(!a.B){a.gb.show();
a.Ta=new g.L(function(){g.M(a.context.I.getRootNode(),g.DQ.IV_DRAWER_OPEN)},0);
a.Ta.start();a.va=g.qu(a.u,"mousewheel",function(k){a.ya.start();k.preventDefault();k=k||window.event;var l=0;"MozMousePixelScroll"==k.type?l=0==(k.axis==k.HORIZONTAL_AXIS)?k.detail:0:window.opera?l=k.detail:l=0==k.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?k.wheelDeltaY/-30:k.wheelDeltaY/-1.2:k.wheelDelta/-1.6:k.wheelDeltaY/-3;if(k=l)a.u.scrollTop+=k});
a.B=!0;var d=g.Vv();d&&a.Ga&&a.K&&g.cw(d,[a.Ga,a.K]);b={TRIGGER_TYPE:b};for(var e=g.r(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.JO||(f.JO=!0,wUa(a.context.logger,f.card.tracking.impression,b)),d&&g.cw(d,[f.card.Pl]);V0(a.I);c&&(a.D=new g.L(function(){a.Ia=a.S;a.qb.focus()},330),a.D.start())}},C1=function(a){a.B&&(a.gb.hide(),g.ru(a.va),a.va=null,g.Hp(a.context.I.getRootNode(),g.DQ.IV_DRAWER_OPEN),a.B=!1,V0(a.I),a.D&&a.D.stop(),a.D=new g.L(function(){a.Ia&&(a.Ia.focus(),a.Ia=null)},330),a.D.start())},
yUa=function(a){g.Gp(a.element,[g.DQ.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.bL(a.I,a.C,5);xUa(a);a.S=g.ci("ytp-cards-button",a.I.getRootNode());a.qb=g.ci("iv-drawer-close-button",a.C);a.isInitialized=!0},xUa=function(a){var b=g.ci("iv-drawer-close-button",a.C);
a.context.j.Na(b,"click",a.gV,a);a.context.j.Na(a.u,"touchend",function(){a.ya.start()});
a.context.j.Na(a.u,"scroll",a.sV,a);a.context.u.subscribe("onHideControls",function(){a.Ma=!0});
a.context.u.subscribe("onShowControls",function(){a.Ma=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.Ma=g.Fp(a.I.getRootNode(),"ytp-autohide")});
a.Z.push(g.Ku("iv-button-shown",a.QW,a));a.Z.push(g.Ku("iv-button-hidden",a.PW,a));a.Z.push(g.Ku("iv-teaser-shown",a.IT,a));a.Z.push(g.Ku("iv-teaser-hidden",a.RW,a));a.Z.push(g.Ku("iv-teaser-clicked",a.HT,a))},zUa=function(a,b){var c,d=null==(c=a.I.getVideoData())?void 0:c.multiMarkersPlayerBarRenderer;
if(null==d?0:d.markersMap){var e;for(c=0;(null==(e=d)?void 0:e.markersMap.length)>c;c++){var f=void 0,k=null==(f=d)?void 0:f.markersMap[c];if("ERROR_CORRECTION_MARKERS"===k.key&&(f=void 0,(k=null==(f=k.value)?void 0:f.markers)&&0<k.length))return d=void 0,b.startMs=(null==(d=k[0].markerRenderer)?void 0:d.timeRangeStartMillis)||0,a.ma=null,!0}}a.ma=b;return!1},E1=function(a,b){if(b.onClickCommand&&b.onClickCommand.changeEngagementPanelVisibilityAction&&"engagement-panel-error-corrections"===b.onClickCommand.changeEngagementPanelVisibilityAction.targetId){a.ma=
b;
var c=!0}else c=!1;if(!c||zUa(a,b))if(c=AUa(a,b)){var d={card:b,qF:c.element,JO:!1};if(!b.onClickCommand){a.isInitialized||yUa(a);vUa(a,b.id);var e=BUa(a,d);g.dc(a.cards,e,0,d);c.Ba(a.u,e);a.HA()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.B||(a.j=d,H1(a),CUa(a,d),B1(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.I.getCurrentTime(),5E3>c&&c>b.startMs&&DUa(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){DUa(a,d)}),H1(a))}},AUa=function(a,b){switch(b.type){case "simple":a=
a.ra;
var c=b.displayDomain?{G:"div",L:"iv-card-image-text",oa:b.displayDomain}:void 0;var d=nUa(b);c={G:"div",Ea:["iv-card"],U:[{G:"a",L:"iv-click-target",W:{href:b.url?r1(b.url)||"":""},U:[v1(b.imageUrl,c),{G:"div",L:"iv-card-content",U:[t1("h2",void 0,b.title),d]}]}]};c=new g.V(c);x1(a,g.bi("iv-click-target",c.element),b,b.url);return c;case "collaborator":return a=a.ra,c={G:"div",Ea:["iv-card","iv-card-channel"],U:[{G:"a",Ea:["iv-click-target"],W:{href:r1(b.url)||"","data-ytid":b.channelId},U:[v1(b.profileImageUrl),
{G:"div",L:"iv-card-content",U:[u1(b),{G:"h2",L:"iv-card-primary-link",oa:b.title},w1(b)]}]}]},c=new g.V(c),x1(a,g.bi("iv-click-target",c.element),b,b.url),c;case "playlist":return a=a.ra,c={G:"div",Ea:["iv-card","iv-card-playlist"],U:[{G:"a",L:"iv-click-target",W:{href:r1(b.url)||""},U:[v1(b.Nz,{G:"div",L:"iv-card-image-overlay",U:[{G:"span",L:"iv-card-playlist-video-count",oa:b.playlistVideoCount}]}),{G:"div",L:"iv-card-content",U:[u1(b),t1("h2","iv-card-primary-link",b.title),w1(b)]}]}]},c=new g.V(c),
x1(a,g.bi("iv-click-target",c.element),b,b.url),c;case "productListing":a=a.ra;var e=!g.Ub(b.offers);c=["iv-card"];d="";var f=nUa(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({G:"div",L:"iv-card-offer-price",oa:f.price}),f.merchant&&e.push({G:"div",L:"iv-card-offer-merchant",oa:f.merchant}),f={G:"div",U:e});e=b.url?r1(b.url)||"":"";c={G:"div",Ea:c,W:{tabindex:"0"},U:[{G:"a",Ea:["iv-card-image","iv-click-target"],W:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{G:"div",L:"iv-card-content",U:[b.sponsored?{G:"div",L:"iv-card-sponsored",U:["Sponsored",{G:"div",L:"iv-ad-info-container",U:[{G:"div",L:"iv-ad-info",oa:"{{adInfo}}"},{G:"div",L:"iv-ad-info-icon-container",U:[{G:"div",L:"iv-ad-info-icon"},{G:"div",L:"iv-ad-info-callout"}]}]}]}:"",{G:"a",L:"iv-click-target",W:{href:e},U:[t1("h2",d,b.title),f]}]}]};c=new g.V(c);d=g.ji("span");g.qi(d,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
c.Nd(d,"adInfo");x1(a,g.bi("iv-click-target",c.element),b,b.url);return c;case "video":return a=a.ra,d=b.videoDuration?{G:"span",L:"iv-card-video-duration",oa:b.videoDuration}:void 0,f=b.isLiveNow?{G:"span",Ea:["yt-badge","yt-badge-live"],oa:"LIVE NOW"}:null,e={G:"div",Ea:["iv-card","iv-card-video"],U:[{G:"a",L:"iv-click-target",W:{href:(null==(c=b.url)?void 0:r1(c))||""},U:[v1(b.Nz,d),{G:"div",L:"iv-card-content",U:[u1(b),t1("h2","iv-card-primary-link",b.title),w1(b),f]}]}]},c=new g.V(e),x1(a,g.bi("iv-click-target",
c.element),b,b.url),c;default:return null}},BUa=function(a,b){if(0===a.cards.length)return 0;
a=g.Rb(a.cards,function(c){return b.card.startMs>c.card.startMs||b.card.startMs===c.card.startMs&&b.card.timestamp>=c.card.timestamp?!0:!1});
return-1===a?0:a+1},EUa=function(a){return a.j?"productListing"===a.j.card.type:g.$l(a.cards,function(b){return"productListing"===b.card.type})},H1=function(a){g.N(a.I.getRootNode(),"ytp-cards-shopping-active",EUa(a))},DUa=function(a,b){if(!g.Fp(a.I.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.Vv(),d=a.j?a.j.card.lf:a.lf;
c&&d&&g.dw(c,[d]);a.j=b;H1(a)}(c=a.isInitialized&&"none"==a.element.style.display)||(c=a.context.I.getPlayerState(),d=0===c&&0===a.context.I.getCurrentTime(),c=!(1===c||3===c||d));c||b.card.teaserDurationMs&&a.I.Kv(!0,{teaserText:b.card.teaserText,durationMs:b.card.teaserDurationMs,onClickCommand:b.card.onClickCommand});a.ib.isActive()||((!a.B||!a.ya.isActive()&&a.Ma)&&CUa(a,b),a.ib.start(910+b.card.teaserDurationMs))}},CUa=function(a,b){a.Y.sb?(b=new $0([0,
a.u.scrollTop],[0,b.qF.offsetTop],600,NTa),a.context.B.Na(b,"animate",function(c){a.u.scrollTop=c.y}),a.context.B.Na(b,"finish",function(c){a.u.scrollTop=c.y}),b.play()):(g.lI(a.Y,!0),a.u.scrollTop=b.qF.offsetTop,g.lI(a.Y,!1))},I1=function(a){return a.j&&a.j.card?a.j.card:a.cards[0]&&a.cards[0].card?a.cards[0].card:null},uUa=function(a,b){return g.Qb(a.cards,function(c){return c.card.id===b})},J1=function(a,b,c){y1.call(this,a,b);
this.annotation=c;this.isActive=!1},FUa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},K1=function(a,b,c){J1.call(this,a,b,c);
this.u=null;this.K=!1;this.B=null;this.C=!1;this.j=this.J=this.D=null},GUa=function(a,b){var c=void 0===c?0:c;
var d=LTa(b).width;g.Um(b,d);c=new b1(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,MTa);g.H(a,c);a.context.B.Na(c,"begin",function(){g.$m(b,!0)});
c.play()},JUa=function(a,b){if(b.channel_name){var c=a.createElement({G:"div",
Ea:["iv-branding-context-name"],oa:b.channel_name}),d=a.createElement({G:"div",Ea:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.tM(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signInUrl,a.context.I),a.j.Ba(d));var f=a.createElement({G:"div",Ea:["iv-branding-context-subscribe-caret"]}),k=a.createElement({G:"div",Ea:["branding-context-container-inner"]});
k.appendChild(f);k.appendChild(c);k.appendChild(d);g.$m(k,!1);var l=a.createElement({G:"div",Ea:["branding-context-container-outer"]});l.appendChild(k);g.Om(l,"right",b.image_width+"px");a.element.appendChild(l);a.B=new g.L(function(){HUa(a,k,l)},500);
g.H(a,a.B);a.context.j.Na(a.element,"mouseover",function(){IUa(a,k,l,f,b.image_height)});
a.context.j.Na(a.element,"mouseout",function(){a.B.start()})}},IUa=function(a,b,c,d,e){a.B.stop();
if(!a.C){var f=g.Zm(b);a.j||(b.style.width=g.Tm(f.width,!0),c.style.width=g.Tm(f.width,!0));g.Om(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.Om(d,"right","1px");a.C=!0;g.$m(b,!0);a.D=new g.L(function(){g.M(this.element,"iv-branding-active")},0,a);
a.D.start()}},HUa=function(a,b,c){g.Hp(a.element,"iv-branding-active");
a.J=new g.L(function(){g.$m(b,!1);a.j||(c.style.width=g.Tm(0,!0))},250);
a.J.start();a.C=!1},KUa=function(a,b,c,d,e,f,k){this.j=a;
this.B=b;this.X=c;this.videoData=d;this.logger=e;this.I=f;this.u=k},L1=function(a,b,c){J1.call(this,a,b,c);
var d=this;this.S=this.isCollapsed=this.Y=!1;this.J=5E3;this.u=this.B=this.j=this.C=null;this.K=this.createElement({G:"div",Ea:["iv-promo-contents"]});this.D=new g.L(function(){d.j.setAttribute("aria-hidden","true");g.$m(d.B,!1);g.$m(d.u,!0)},700,this);
g.H(this,this.D)},LUa=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.J=b.collapsedelay_ms||a.J;var d=["iv-promo","iv-promo-inactive"];a.element.setAttribute("aria-hidden","true");a.element.setAttribute("aria-label","Promotion");a.element.tabIndex=0;var e=lUa(a.annotation),f=b.image_url;if(f){var k=a.createElement({G:"div",Ea:["iv-promo-img","iv-click-target"]});f=a.createElement({G:"img",W:{src:f,"aria-hidden":"true"}});k.appendChild(f);b.video_duration&&
!b.is_live?(f=a.createElement({G:"span",L:"iv-promo-video-duration",oa:b.video_duration}),k.appendChild(f)):b.playlist_length&&(f=a.createElement({G:"span",L:"iv-promo-playlist-length",oa:b.playlist_length.toString()}),k.appendChild(f));e&&z1(a,k,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({G:"a",L:"iv-promo-txt"}),g.yh(f,r1(e)),a.j=f):a.j=a.createElement({G:"div",L:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({G:"p",U:[{G:"strong",
oa:b.text_line_1}]});var m=a.createElement({G:"p",U:[{G:"span",L:"iv-promo-link",oa:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({G:"button",Ea:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({G:"button",Ea:["iv-button","iv-promo-button"],U:[{G:"span",L:"iv-button-content",oa:f}]});var p=a.createElement({G:"div",L:"iv-promo-button-container"});p.appendChild(f);e&&z1(a,a.element,e,a.annotation.id,b.session_data,void 0,c)}g.M(a.j,
"iv-click-target");e&&z1(a,a.j,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({G:"p",U:[{G:"span",oa:b.text_line_1}]}),m=a.createElement({G:"p",U:[{G:"strong",oa:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({G:"span",Ea:["yt-badge","iv-promo-badge-live"],oa:"LIVE NOW"})),g.M(a.j,"iv-click-target"),e&&z1(a,a.j,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.j.appendChild(l);m&&a.j.appendChild(m);a.K.appendChild(a.j);p&&
a.K.appendChild(p);c=a.createElement({G:"div",L:"iv-promo-actions"});a.u=a.createElement({G:"button",Ea:["iv-promo-expand","ytp-button"]});a.u.title="Expand";a.context.j.Na(a.u,"click",function(q){M1(a,5E3,q)});
c.appendChild(a.u);g.$m(a.u,!1);a.context.j.Na(a.element,"mouseover",a.YV,a);a.context.j.Na(a.element,"mouseout",a.XV,a);a.context.j.Na(a.element,"touchend",function(q){M1(a,5E3,q)});
a.B=a.createElement({G:"button",Ea:["iv-promo-close","ytp-button"]});a.B.title="Close";a.context.j.Na(a.B,"click","cta"===a.annotation.style&&b.text_line_3?a.TV:a.SV,a);c.appendChild(a.B);g.Gp(a.element,d);k&&(a.element.appendChild(k),n&&k.appendChild(n));a.element.appendChild(a.K);a.element.appendChild(c)},M1=function(a,b,c){c.stopPropagation();
MUa(a);NUa(a,b);a.j.focus()},OUa=function(a){a.isCollapsed||a.S||a.C||(g.M(a.element,"iv-promo-collapsed"),a.isCollapsed=!0,a.D.start())},MUa=function(a){a.D.stop();
a.isCollapsed&&(g.Ip(a.element,["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.$m(a.u,!1),g.$m(a.B,!0))},NUa=function(a,b){a.C||(a.C=g.Li(function(){N1(this);
OUa(this)},b,a))},N1=function(a){a.C&&(g.C.clearTimeout(a.C),a.C=null)},PUa=function(a){this.I=a},wUa=function(a,b,c){b&&(c?O1(a,b.map(function(d){return g.rp(d,c)})):O1(a,b))},O1=function(a,b,c,d){var e=1,f=void 0,k=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(k),l=!0,c())};
k=setTimeout(function(){l=!0;c()},1E3)}b=g.r(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.Pt(m,f);d&&(e++,0!==d&&a.I.sendVideoStatsEngageEvent(d,f))},P1=function(a){g.oL.call(this,a);
var b=this;this.loadNumber=0;this.J={};this.logger=new PUa(this.player);this.D=new g.lA(this);this.C=this.Km=null;this.events=new g.lA(this);this.K=this.j=null;this.S=[];g.H(this,this.D);this.D.T(this.player,"onVideoAreaChange",function(){b.ea("onVideoAreaChange")});
this.D.T(this.player,"onHideControls",function(){b.ea("onHideControls")});
this.D.T(this.player,"onShowControls",function(){b.ea("onShowControls")});
this.D.T(this.player,"resize",function(d){b.ea("resize",d)});
this.D.T(this.player,"presentingplayerstatechange",function(d){b.ea("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.JT,this);this.subscribe("resize",this.uC,this);this.player.V().Z.subscribe("vast_info_card_add",this.VP,this);g.H(this,this.events);this.Y=this.createElement({G:"div",L:"video-custom-annotations"});this.u=new g.V({G:"div",Ea:["ytp-player-content","ytp-iv-player-content"]});g.H(this,this.u);g.bL(this.player,this.u.element,4);this.u.hide();this.B=new g.V({G:"div",Ea:["ytp-iv-video-content"]});g.H(this,this.B);a=this.createElement({G:"div",L:"video-annotations"});
a.appendChild(this.Y);this.B.element.appendChild(a);this.Ns()&&this.load();var c=this.createElement({G:"style"});(g.Xh("HEAD")[0]||document.body).appendChild(c);g.yf(this,function(){g.ni(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},QUa=function(a){a=a.createElement({G:"div",
Ea:["annotation","annotation-type-custom"]});g.$m(a,!1);return a},RUa=function(a,b){b=!b.isCued()&&!g.U(b,1024);
g.lI(a.u,b);g.lI(a.B,b)},SUa=function(a,b){for(var c={},d=g.r(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Oa(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(SUa(a,e))}return c},VUa=function(a){var b=a.player.getVideoData();
if(b.Ua){var c=a.player.V().Z.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,k){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(k=g.Cr(k)&&k.responseXML?k.responseXML:null)&&Q1(a,k)}};
g.Yr()&&(d.onFinish=TUa(a,d.onFinish));d.postParams={ic_only:"1"};UUa(d,c);g.Ir(b.Ua,d)}}},UUa=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.ox&&(a.postParams.ic_coll=b.ox);b.MA&&(a.postParams.ic_xml=b.MA);b.Qz&&(a.postParams.ic_track=b.Qz)},WUa=function(a){var b=new g.V({G:"div"});
g.$m(b.element,!1);var c=new D1(a.player,b.element,R1(a));g.H(c,b);b.Ba(a.u.element);c.Az();return c},R1=function(a){if(!a.K){var b=new c1(a);
g.H(a,b);var c=new g.Xk(a);g.H(a,c);a.K=new KUa(b,c,a.player.V(),a.player.getVideoData(),a.logger,a.player,a.Oe)}return a.K},Q1=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.Vv();if(e){var f=g.Uv();f&&g.Zv(void 0,e,f,[g.Ov(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=SUa(a,b[d]);e=null;try{if(f){var k=f.id,l=/.+/;var m="string"===typeof k&&null!=l&&null!=k&&k.match(l)?k:"";var n=q1(f.type,XUa),p=q1(f.style,YUa),q=cUa(f.data),t=0!==q.length?JSON.parse(q):{};var v=f.action;f=iUa;if(null==v)var x=null;else if(g.Ma(v)){l=[];for(var y=g.r(v),z=y.next();!z.done;z=y.next()){var E=f(z.value);
E&&l.push(E)}x=l}else{var I=f(v);x=I?[I]:[]}e=m&&n?new jUa(m,n,p,x,t):null}else e=null}catch(za){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var K=QUa(f),P=null;switch(l.type){case "branding":if(f.player.V().Oc)break;f.u.element.appendChild(K);P=new K1(K,R1(f),l);break;case "promotion":g.bL(f.player,K,4),P=new L1(K,R1(f),l)}P&&P.Az();if(f=P)g.H(a,f),a.J[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.j||(a.j=WUa(a),g.H(a,a.j));if("card"===e.type){c=a.j;var Y=e&&e.data&&e.data.card_type;
f=e.data;if(Y)switch(l=f.tracking||{},l={impression:l.impression,click:l.click,close:l.close,kR:l.teaser_impression,nD:l.teaser_click},K=f.tracking_params||{},P=null,Y){case "collaborator":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Pl:K.card?g.Ov(K.card):null,gj:K.teaser?g.Ov(K.teaser):null,lf:K.icon?g.Ov(K.icon):null,
channelId:f.channel_id,customMessage:f.custom_message?f.custom_message:null,profileImageUrl:f.image_url,title:f.title,metaInfo:f.meta_info,url:s1({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};E1(c,e);break;case "playlist":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,
Pl:K.card?g.Ov(K.card):null,gj:K.teaser?g.Ov(K.teaser):null,lf:K.icon?g.Ov(K.icon):null,Nz:f.image_url,playlistVideoCount:f.playlist_video_count,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,url:s1({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};E1(c,e);break;case "productListing":f.signin_url&&(P=s1({target:"current",value:f.signin_url}));Y=[];for(var J=f.offers||[],pa=0;pa<J.length;pa++)Y.push(new oUa(g.Nh(J[pa].merchant),
g.Nh(J[pa].price)));e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Pl:K.card?g.Ov(K.card):null,gj:K.teaser?g.Ov(K.teaser):null,lf:K.icon?g.Ov(K.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,nx:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?
f.custom_message:null,url:s1({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),ija:P,hja:f.signin_title?f.signin_title:void 0,gja:f.signin_message?f.signin_message:void 0,offers:Y,onClickCommand:null};E1(c,e);break;case "simple":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Pl:K.card?g.Ov(K.card):
null,gj:K.teaser?g.Ov(K.teaser):null,lf:K.icon?g.Ov(K.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,nx:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:s1({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};E1(c,e);break;case "video":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,
startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Pl:K.card?g.Ov(K.card):null,gj:K.teaser?g.Ov(K.teaser):null,lf:K.icon?g.Ov(K.icon):null,Nz:f.image_url,videoDuration:f.video_duration||null,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,isLiveNow:!!f.is_live_now,url:s1({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null},E1(c,e)}}else sUa(a.j,e);c=
!0}}c&&(V0(a.player),a.uC())},ZUa=function(a,b){var c=!1;
a.j||(a.j=WUa(a),g.H(a,a.j));for(var d=g.r(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(tUa(a.j,e.cardRenderer),c=!0);c&&(c=a.j,d=b.headerText?g.Sw(b.headerText):"",g.qi(c.Hb,d),c.S&&c.S.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Ga=b.trackingParams?g.Ov(b.trackingParams):null,c.K=b.closeButton.infoCardIconRenderer.trackingParams?g.Ov(b.closeButton.infoCardIconRenderer.trackingParams):null,c.lf=b.icon.infoCardIconRenderer.trackingParams?
g.Ov(b.icon.infoCardIconRenderer.trackingParams):null,V0(a.player),a.uC())},$Ua=function(a,b,c,d,e){if(!a.player.V().Oc){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new fUa("openUrl","click",new dUa("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0)));var k=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:k.height,image_type:1,image_url:k.url,image_width:k.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;var l;b=b.subscribeButton.subscribeButtonRenderer;k=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.Sw(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(k=g.Sw(b.subscriberCountText))):(b.subscriberCountText&&(e=g.Sw(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(k=g.Sw(b.subscriberCountWithSubscribeText)));if(b.signInEndpoint&&b.signInEndpoint.webNavigationEndpointData&&
b.signInEndpoint.webNavigationEndpointData.url)var m=b.signInEndpoint.webNavigationEndpointData.url;else{var n,p;m=(null==(l=b.signInEndpoint)?void 0:null==(n=l.commandMetadata)?void 0:null==(p=n.webCommandMetadata)?void 0:p.url)||""}l={subscribeText:g.Sw(b.unsubscribedButtonText),subscribeCount:e||"",unsubscribeText:g.Sw(b.subscribedButtonText),unsubscribeCount:k||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:m};d.standalone_subscribe_button_data=l}f=new jUa(c,
"branding","branding",f,d);l=QUa(a);a.u.element.appendChild(l);f=new K1(l,R1(a),f);f.Az();g.H(f,f);a.J[c]=f}},TUa=function(a,b){return function(){var c=g.Ca.apply(0,arguments);
a.isDisposed()||a.S.push(g.vp.Sg(function(){b.apply(null,g.u(c))}))}},aVa=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.VK.prototype.Kv=g.ca(17,function(a,b){var c=g.FL(this.rb());c&&c.Kv(a,b)});
var X0={},Y0=null;g.Va($0,g.Qp);g.h=$0.prototype;g.h.getDuration=function(){return this.duration};
g.h.play=function(a){if(a||0==this.j)this.progress=0,this.coords=this.u;else if(this.Nc())return!1;Z0(this);this.startTime=a=g.Ua();-1==this.j&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.pC();this.xj("play");-1==this.j&&this.xj("resume");this.j=1;var b=g.Qa(this);b in X0||(X0[b]=this);PTa();QTa(this,a);return!0};
g.h.stop=function(a){Z0(this);this.j=0;a&&(this.progress=1);RTa(this,this.progress);this.xj("stop");this.Sy()};
g.h.pause=function(){this.Nc()&&(Z0(this),this.j=-1,this.xj("pause"))};
g.h.qa=function(){0==this.j||this.stop(!1);this.xj("destroy");$0.Le.qa.call(this)};
g.h.destroy=function(){this.dispose()};
g.h.sE=function(){this.xj("animate")};
g.h.xj=function(a){this.dispatchEvent(new STa(a,this))};
g.Va(STa,g.zf);g.Va(a1,$0);a1.prototype.C=function(){};
a1.prototype.sE=function(){this.C();a1.Le.sE.call(this)};
a1.prototype.Sy=function(){this.C();a1.Le.Sy.call(this)};
a1.prototype.pC=function(){this.C();a1.Le.pC.call(this)};
g.Va(b1,a1);b1.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.w(c1,g.G);c1.prototype.Na=function(a,b,c,d){c=(0,g.Sa)(c,d||this.u);a=g.qu(a,b,c);this.j.push(a);return a};
c1.prototype.aC=function(a,b,c,d){c=(0,g.Sa)(c,d||this.u);a=g.zoa(a,b,c);this.j.push(a);return a};
c1.prototype.xc=function(a){g.ru(a);g.Yb(this.j,a)};
c1.prototype.qa=function(){g.ru(this.j);this.j.length=0;g.G.prototype.qa.call(this)};g.w(g1,g.oL);g.h=g1.prototype;g.h.load=function(){g.oL.prototype.load.call(this);if(!h1(this)){var a=g.pwa(this.player.getVideoData());a?(a=f1(a,UTa(this)),i1(this,a,!1)):VTa(this)}};
g.h.unload=function(){i1(this,null);this.B&&(this.B.abort(),this.B=null);g.oL.prototype.unload.call(this)};
g.h.Yf=function(a,b){return h1(this)?"loadCustomEndscreenRenderer"===a?(a=f1(b,"new"),i1(this,a),!0):null:null};
g.h.getOptions=function(){return h1(this)?["loadCustomEndscreenRenderer"]:[]};
g.h.xb=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<bVa.length;f++){var k=Math.abs(b.width-bVa[f]);if(-1===e||d>=k)e=f,d=k}d=cVa[e];this.u&&g.Om(this.u.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
k=this.D[f],e&&k){var l=k.width*c/k.aspectRatio;f=Math.round(l*a.height);var m=a.left+Math.round(k.left*a.width),n=a.top+Math.round(k.top*a.height);g.Ym(e.element,Math.round(k.width*a.width),f);g.Um(e.element,m,n);g.Ip(e.element,dVa);m=k.left+k.width/2;k=k.top+l/2;g.M(e.element,.5>=m&&.5>=k?"ytp-ce-top-left-quad":.5<m&&.5>=k?"ytp-ce-top-right-quad":.5>=m&&.5<k?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Ip(e.element,cVa);g.M(e.element,d);(e=g.Yh(document,"div","ytp-ce-expanding-overlay-body",
e.element)[0])&&g.Om(e,"height",f+"px")}}}}};
g.h.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())p1(this,this.endscreen.impressionUrls),(a=g.Vv())&&this.endscreen.visualElement&&g.$v(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.D[a];g.M(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.M(b,"ytp-ce-shown");p1(this,c.impressionUrls);(b=g.Vv())&&g.$v(b,c.visualElement);this.player.V().B&&this.player.Ka("endscreenelementshown",
a)}};
g.h.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.j[a];g.Hp(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.Hp(b,"ytp-ce-shown");this.player.V().B&&this.player.Ka("endscreenelementhidden",a)}};
g.h.n_=function(a){var b=this;a.target===window&&(new g.L(function(){for(var c=g.r(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.Ip(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var bVa=[346,426,470,506,570,640,853,1280,1920],cVa="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),dVa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var eUa={v6:"current",Zba:"new"};var gUa={CLOSE:"close",tca:"openUrl",SUBSCRIBE:"subscribe"},hUa={d3:"click",CLOSE:"close",Y7:"hidden",Vda:"rollOut",Wda:"rollOver",Sea:"shown"};var YUa={V1:"anchored",cS:"branding",CHANNEL:"channel",u6:"cta",b8:"highlightText",E9:"label",PLAYLIST:"playlist",nda:"popup",dfa:"speech",SUBSCRIBE:"subscribe",zfa:"title",VIDEO:"video",hha:"website"},XUa={cS:"branding",O2:"card",N6:"drawer",a8:"highlight",jaa:"marker",xda:"promotion",TEXT:"text",Lha:"widget"};g.w(y1,g.G);g.h=y1.prototype;g.h.addCueRange=function(a,b,c,d,e){a=new g.Lw(a,b,{id:c,namespace:"annotations_module"});d&&this.Ua.set(a,d);e&&this.Za.set(a,e);this.context.I.je([a])};
g.h.Az=function(){this.context.u.subscribe("resize",this.HA,this)};
g.h.tE=function(a,b,c,d,e,f){if(this.kb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.h.show=function(){};
g.h.hide=function(){};
g.h.destroy=function(){g.ni(this.element)};
g.h.HA=function(){};
g.h.navigate=function(a,b,c,d){var e=this,f=r1(a);if(f){var k=qUa(f,a.target),l=function(){a.j&&e.context.I.pauseVideo();var m=e.context.videoData.D||!1,n=g.qr(f||"");m&&n&&(n.v||n.list)?e.context.I.ql(n.v,b,n.list,!1):g.wJ(f||"","current"===k?"_top":void 0,b)};
"new"===k&&(l(),l=null);O1(this.context.logger,c,l,d);pUa(f)||(c=g.Vv(),d=b.itct,c&&d&&g.ew(c,g.Ov(d)))}};
g.h.qa=function(){this.Ua.clear();this.Za.clear();g.G.prototype.qa.call(this)};
g.h.createElement=function(a){a=new g.V(a);g.H(this,a);return a.element};g.w(D1,y1);g.h=D1.prototype;g.h.Fp=function(){this.ma&&E1(this,this.ma)};
g.h.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.I.getRootNode())?(a=g.Zm(a),a=173<a.width&&173<a.height):a=!1;return a};
g.h.HA=function(){var a=this.isAvailable();g.$m(this.element,a);g.N(this.context.I.getRootNode(),g.DQ.IV_DRAWER_ENABLED,a);V0(this.I)};
g.h.destroy=function(){this.I.Kv(!1);try{this.I.getRootNode().removeChild(this.C)}catch(a){}g.Lu(this.Z);g.ru(this.va);this.Ta&&this.Ta.dispose();this.D&&this.D.dispose();y1.prototype.destroy.call(this)};
g.h.gV=function(){if(this.B){O1(this.context.logger,I1(this).tracking.close);var a=g.Vv();a&&this.K&&g.ew(a,this.K);C1(this)}};
g.h.sV=function(){g.N(this.C,"iv-drawer-scrolled",0<this.u.scrollTop)};
g.h.QW=function(){var a=g.Vv(),b=I1(this);b=b?b.lf:this.lf;a&&b&&g.cw(a,[b])};
g.h.PW=function(){var a=g.Vv(),b=I1(this);b=b?b.lf:this.lf;a&&b&&g.dw(a,[b])};
g.h.IT=function(){var a=I1(this);O1(this.context.logger,a.tracking.kR);var b=g.Vv();b&&a&&g.cw(b,[a.gj,a.lf])};
g.h.RW=function(){var a=g.Vv(),b=I1(this);a&&b&&g.dw(a,[b.gj])};
g.h.HT=function(a){var b=I1(this),c=g.Vv();this.j?a?(a=this.context.logger,O1(a,b.tracking.nD),a.I.sendVideoStatsEngageEvent(4,void 0),c&&b.gj&&g.ew(c,b.gj)):(a=this.context.logger,O1(a,b.tracking.nD),a.I.sendVideoStatsEngageEvent(4,void 0),c&&b.lf&&g.ew(c,b.lf)):(a=this.context.logger,O1(a,b.tracking.nD),a.I.sendVideoStatsEngageEvent(4,void 0),c&&this.lf&&g.ew(c,this.lf))};g.w(J1,y1);J1.prototype.Az=function(){y1.prototype.Az.call(this);FUa(this)};
J1.prototype.show=function(){y1.prototype.show.call(this);var a=g.Vv(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.cw(a,[g.Ov(b.itct)])};
J1.prototype.hide=function(){y1.prototype.hide.call(this);var a=g.Vv(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.dw(a,[g.Ov(b.itct)])};g.w(K1,J1);
K1.prototype.show=function(){if(!this.isActive){J1.prototype.show.call(this);if(!this.K){g.M(this.element,"iv-branding");var a=this.annotation.data;this.u=this.createElement({G:"img",Ea:["branding-img","iv-click-target"],W:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.$m(this.u,!1);var b=this.context.X.N("html5_player_branding_button_killswitch")?this.createElement({G:"div",Ea:["branding-img-container"]}):this.createElement({G:"button",Ea:["branding-img-container",
"ytp-button"]});b.appendChild(this.u);this.element.appendChild(b);var c=lUa(this.annotation);c&&(b=this.context.X.N("html5_player_branding_button_killswitch")?this.u:b,z1(this,b,c,this.annotation.id,a.session_data));JUa(this,a);this.K=!0}g.$m(this.element,!0);this.isActive=!0;this.u&&GUa(this,this.u)}};
K1.prototype.hide=function(){this.isActive&&(J1.prototype.hide.call(this),g.$m(this.element,!1),this.isActive=!1)};
K1.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);J1.prototype.destroy.call(this)};g.w(L1,J1);g.h=L1.prototype;g.h.show=function(){this.isActive||(J1.prototype.show.call(this),this.Y||(LUa(this),this.Y=!0),g.$m(this.element,!0),g.Li(function(){g.Hp(this.element,"iv-promo-inactive")},100,this),this.element.removeAttribute("aria-hidden"),this.isActive=!0,N1(this),MUa(this),NUa(this,this.J))};
g.h.hide=function(){this.isActive&&(g.M(this.element,"iv-promo-inactive"),this.isActive=!1,this.element.setAttribute("aria-hidden","true"))};
g.h.tE=function(a,b,c,d,e,f){return this.isCollapsed?!1:J1.prototype.tE.call(this,a,b,c,d,e,f)};
g.h.YV=function(a){this.S=!0;M1(this,500,a)};
g.h.XV=function(){this.S=!1;OUa(this)};
g.h.SV=function(a){a.stopPropagation();this.hide()};
g.h.TV=function(a){a.stopPropagation();N1(this);this.isCollapsed=!0;g.M(this.element,"iv-promo-collapsed-no-delay");this.D.start()};
g.h.destroy=function(){this.D.dispose();J1.prototype.destroy.call(this)};g.w(P1,g.oL);g.h=P1.prototype;g.h.Yf=function(a,b){if(!aVa(this.player.V().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.t_(b))&&Q1(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&(vUa(this.j,b),V0(this.player)),!0}return null};
g.h.getOptions=function(){return aVa(this.player.V().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.h.Ns=function(){var a=this.player.V(),b=this.player.getVideoData();return b.D&&a.pfpChazalUi?!1:1===(a.annotationsLoadPolicy||b.annotationsLoadPolicy)&&!b.eP||a.Z.get(b.videoId)||g.xE(b)||g.yE(b)?!0:!1};
g.h.uC=function(){if(this.B){var a=this.player.Xa().getVideoContentRect(!0);g.Ym(this.B.element,a.width,a.height);g.Um(this.B.element,a.left,a.top)}if(this.j){var b=this.player.Gk();a=this.j;b=b.width;g.N(a.C,"iv-drawer-small",426>=b);g.N(a.C,"iv-drawer-big",1280<=b)}};
g.h.JT=function(a){RUa(this,a.state);g.U(a.state,2)&&(this.Qh()&&this.Ol()&&2!==this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.Kv(!1))};
g.h.load=function(){function a(k){var l=b.loadNumber;b.C=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(k=g.Cr(k)&&k.responseXML?k.responseXML:null)&&(Q1(b,k),g.M(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.oL.prototype.load.call(this);RUa(this,this.player.yb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.Yr()&&(a=TUa(this,a));var e={format:"XML",onFinish:a,onError:function(){b.C=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.V().Z.get(d);f&&UUa(e,f);f=f&&(f.MA||f.ox);if(!c.Ym||f)c.Ua?this.C=g.Ir(c.Ua,e):(this.Km=function(){b.onVideoDataChange(e)},this.player.addEventListener("videodatachange",this.Km));
g.bL(this.player,this.B.element,4);this.uC();(f=g.xE(c))&&ZUa(this,f);(f=g.yE(c))&&f.featuredChannel&&$Ua(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null)};
g.h.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Ua&&(this.Km&&(this.player.removeEventListener("videodatachange",this.Km),this.Km=null),this.C=g.Ir(b.Ua,a))};
g.h.unload=function(){this.player.Nf("annotations_module");for(var a=g.r(Object.keys(this.J)),b=a.next();!b.done;b=a.next())this.J[b.value].destroy();this.K=null;this.j&&(this.j.destroy(),this.j=null,V0(this.player));this.C&&(this.C.abort(),this.C=null);this.J={};this.u.hide();g.oL.prototype.unload.call(this);this.B.detach();this.Km&&(this.player.removeEventListener("videodatachange",this.Km),this.Km=null)};
g.h.VP=function(a){a===this.player.getVideoData().videoId&&(this.loaded?VUa(this):this.load())};
g.h.Qh=function(){return!!this.j&&this.j.isAvailable()};
g.h.Ol=function(){return!!this.j&&this.j.B};
g.h.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.Qh();this.j&&(a?c?B1(this.j,c,b):B1(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):C1(this.j))};
g.h.Kv=function(a,b){this.player.ea(a?"cardsteasershow":"cardsteaserhide",b)};
g.h.qa=function(){this.player.V().Z.unsubscribe("vast_info_card_add",this.VP,this);g.Hp(this.player.getRootNode(),g.DQ.IV_DRAWER_OPEN);for(var a=this.S,b=g.vp,c=0,d=a.length;c<d;c++)b.vj(a[c]);this.S.length=0;g.oL.prototype.qa.call(this)};
g.h.createElement=function(a){a=new g.V(a);g.H(this,a);return a.element};g.nL("annotations_module",P1);g.nL("creatorendscreen",g1);})(_yt_player);
